PACKAGE_NAME="phytium-eth"
PACKAGE_VERSION="1.0"

# 这里的名字必须与.ko 文件名一致
BUILT_MODULE_NAME[0]="dwmac-phytium"

# 编译时自动传入当前内核版本的路径
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make clean"
# 模块安装的目标位置（通常放在 updates 或者 extramodules 下）
DEST_MODULE_LOCATION[0]="/updates/"
# 这一行最关键：内核更新时自动触发编译！
AUTOINSTALL="yes"
